# default config
defaults:
  - db: default
  - data: default
  - paths: default
  - tests: default
  - models: default
  - logging: default
  - features: default
  - training: default
  - evaluation: default
  - _self_

# metadata project config
project:
  name: "Vietnam Coffee Branding"
  version: "0.1.0"
  description: "Production-grade DS project"
  author: "Bao Nguyen Duc Gia"
  seed: 42

# env config
env: local
debug: false
