# root config
root: ${hydra:runtime.cwd}

data:
  root: ${paths.root}/data

src:
  root: ${paths.root}/src


models:
  root: ${paths.root}/model

reports:
  root: ${paths.root}/reports
  figures: ${paths.root}/reports/figures
  metrics: ${paths.root}/reports/metrics
  html: ${paths.root}/reports/html

scripts:
  root: ${paths.root}/scripts
